{
 "title": "Nginx-Geo-Anaylzer",
 "description": "A non-intrusive Nginx log analyzer with geographical insights. Github Repo: https://github.com/LiangrunDa/nginx-geo-analyzer",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": {
     "query": "SHOW TAG VALUES FROM \"geo-log\" WITH KEY = \"country\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geo-log",
     "query": "SELECT sum(\"count\") AS \"metric\" FROM \"geo-log\" WHERE $timeFilter AND country =~ /^${country}/ GROUP BY \"geohash\", \"city\", \"postal_code\", \"longitude\", \"latitude\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Visited Path",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geo-log",
     "query": "SELECT SUM(count) FROM \"geo-log\" WHERE $timeFilter AND country =~ /^${country}/ GROUP BY path",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Countries",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geo-log",
     "query": "SELECT COUNT(count) \nFROM \"geo-log\"\nWHERE $timeFilter AND country =~ /^${country}/\nGROUP BY country\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Influx data",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "geo-log",
     "query": "SELECT * FROM \"geo-log\" WHERE $timeFilter AND country =~ /^${country}/ GROUP BY \"continent\", \"country\", \"state\", \"city\", \"postal_code\", \"ip\", \"latitude\", \"longitude\", \"method\", \"path\", \"referer\", \"status\", \"user_agent\", \"bytes_sent\" ",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" }
      ],
      [
       { "params": [ "ip" ], "type": "field" }
      ],
      [
       { "params": [ "ip" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}